### ISSUE TITLE
Yolo v4 or v5

### ISSUE THREAD

**Issue by j3vr0n** [tucan9389/ObjectDetection-CoreML#4]
Do you know if this works with Yolo v4 or V5?

**Comment by tucan9389** [comment]
No, but I want to support it. Do you have mlmodel? I knew that there are some issues during converting yolov5. If anyone has the mlmodel, please share 🙇‍♂️

**Comment by dclcs** [comment]
I use model in  [yolov5](https://github.com/ultralytics/yolov5/issues/251)


![截屏2021-08-06 下午12 28 02](https://user-images.githubusercontent.com/43787815/128456052-aa1948de-e28b-4689-80b4-9de20a11c486.png)

**Comment by tucan9389** [comment]
@dclcs 

> I use model in [yolov5](https://github.com/ultralytics/yolov5/issues/251)

Nice! Can you share the link of the yolov5 mlmodel which I can download?
And if you can, could you make a PR using the model in my repo?

**Comment by tucan9389** [comment]
## YOLOv5

### Clone and install pre-requirements

> Note that you should clone `mshamash/yolov5` repo and checkout `fix/coreml_export_nms_layer` branch,
> instead of the original repo (`ultralytics/yolov5`)

```shell
git clone https://github.com/mshamash/yolov5
cd yolov5
git checkout fix/coreml_export_nms_layer
pip install -qr requirements.txt  # install
```

### Export to Core ML model

```shell
python export.py --weights yolov5n.pt --include coreml
python export.py --weights yolov5s.pt --include coreml
python export.py --weights yolov5m.pt --include coreml
python export.py --weights yolov5l.pt --include coreml
python export.py --weights yolov5x.pt --include coreml
```

### Check the model input/output with https://netron.app

> yolov5s.mlmodel example

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/37643248/188037027-1b639615-2b90-47b4-9dd4-53f8e5fb5b41.png">

**Comment by tucan9389** [comment]
## Class names of YOLOv5's pre-trained with COCO dataset

- https://github.com/ultralytics/yolov5/blob/9da6d0f9f5bc37fa386b7b82d2a963f94650949a/data/coco.yaml#L17-L97
- 80 classes

**Comment by tucan9389** [comment]
https://github.com/tucan9389/ObjectDetection-CoreML/issues/6
I'll maintain this feature on above issue.
